apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-collector
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-collector
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create", "delete", "get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: event-collector
subjects:
  - kind: ServiceAccount
    name: event-collector
    namespace: monitoring
---
apiVersion: v1
data:
  config.json: |-
    {
        "log": "info",
        "receivers": {
            "elasticsearch": {
                "addresses": [
                    "http://es:9200"
                ],
                "index": "demo_k8s_event",
                "username": "username",
                "password": "password"
            },
            "stdout": false
        }
    }
kind: ConfigMap
metadata:
  name: event-collector-cm
  namespace: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-collector
  namespace: monitoring
  labels:
    app: event-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-collector
  template:
    metadata:
      labels:
        app: event-collector
    spec:
      containers:
        - name: collector
          image: abowloflrf/k8s-event-collector:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: config-volume
              mountPath: /etc/event-collector
      serviceAccountName: event-collector
      volumes:
        - name: config-volume
          configMap:
            name: event-collector-cm
